# https://goframe.org/docs/web/server-config-file-template
server:
  address:     ":8001"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/moyu"
        descriptionTag: true

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    #link: "mysql:root:123456@tcp(127.0.0.1:3306)/scaffold"
    link: "mysql:root:123456@tcp(127.0.0.1:3306)/moyu"


logs:
  prefix: "[moyu]"


utils:
  jwt_secret: linganguliguliguacha
  jwt_expire: 3600  #单位:小时