// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ping

import (
	"scaffold/api/ping"
)

type ControllerV1 struct{}

func NewV1() ping.IPingV1 {
	return &ControllerV1{}
}

type ControllerV2 struct{}

func NewV2() ping.IPingV2 {
	return &ControllerV2{}
}
